amcl:
  ros__parameters:
    use_sim_time: false
    base_frame_id: base_link
    odom_frame_id: odom
    global_frame_id: map
    scan_topic: /scan
    min_particles: 500
    max_particles: 2000
    update_min_d: 0.05
    update_min_a: 0.05

map_server:
  ros__parameters:
    # 런치에서 map:= 인자로 덮어씀. 기본값 예시만 유지.
    yaml_filename: "/home/yoo/workspace/dolchair_ws/config/maps/gongA_map.yaml"

global_costmap:
  ros__parameters:
    global_frame: map
    robot_base_frame: base_link
    use_sim_time: false
    update_frequency: 5.0
    publish_frequency: 2.0
    rolling_window: false
    resolution: 0.05
    track_unknown_space: false
    plugins: ["static_layer", "inflation_layer"]

    static_layer:
      plugin: "nav2_costmap_2d::StaticLayer"
      map_subscribe_transient_local: true

    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      inflation_radius: 0.5
      cost_scaling_factor: 2.5

local_costmap:
  ros__parameters:
    global_frame: odom
    robot_base_frame: base_link
    use_sim_time: false
    update_frequency: 10.0
    publish_frequency: 5.0
    rolling_window: true
    width: 6.0
    height: 6.0
    resolution: 0.05
    plugins: ["obstacle_lidar", "obstacle_depth", "voxel_layer", "inflation_layer"]

    obstacle_lidar:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      observation_sources: scan
      scan:
        topic: /scan
        sensor_frame: laser_frame
        data_type: LaserScan
        marking: true
        clearing: true
        obstacle_range: 4.0
        raytrace_range: 4.5

    obstacle_depth:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      observation_sources: depth_cloud
      depth_cloud:
        topic: /camera/depth/color/points
        sensor_frame: camera_link
        data_type: PointCloud2
        marking: true
        clearing: true
        obstacle_range: 3.5
        raytrace_range: 4.0
        min_obstacle_height: 0.02
        max_obstacle_height: 1.5

    voxel_layer:
      plugin: "nav2_costmap_2d::VoxelLayer"
      origin_z: 0.0
      z_voxels: 16
      z_resolution: 0.075
      max_obstacle_height: 1.6
      unknown_threshold: 10
      mark_threshold: 2
      observation_sources: depth_cloud
      depth_cloud:
        topic: /camera/depth/color/points
        data_type: PointCloud2
        marking: true
        clearing: true

    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      inflation_radius: 0.5
      cost_scaling_factor: 2.5

planner_server:
  ros__parameters:
    expected_planner_frequency: 5.0
    use_sim_time: false
    planner_plugins: ["GridBased"]

    GridBased:
      plugin: "nav2_smac_planner/SmacPlannerHybrid"
      tolerance: 0.15
      downsample_costmap: false
      allow_unknown: false
      max_iterations: 10000
      max_on_approach_iterations: 1000
      minimum_turning_radius: 0.6
      motion_model_for_search: "DUBIN"
      cost_travel_multiplier: 2.0
      cache_obstacle_footprint: true

lifecycle_manager:
  ros__parameters:
    autostart: true
    node_names: ["map_server", "amcl", "planner_server", "global_costmap", "local_costmap"]

