ekf_filter_node:
  ros__parameters:
    frequency: 50.0
    two_d_mode: true
    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # LiDAR odometry input (rf2o or other odom source)
    odom0: /odom
    odom0_config: [true,  true,  false,   # x y z
                   false, false, true,    # roll pitch yaw (yaw only)
                   true,  true,  false,   # vx vy vz
                   false, false, true,    # vroll vpitch vyaw (yaw rate)
                   false, false, false]   # ax ay az

    # IMU input
    imu0: /imu/data
    imu0_differential: false
    imu0_remove_gravitational_acceleration: true
    imu0_config: [false, false, false,
                  false, false, true,     # yaw
                  false, false, false,
                  false, false, true,     # yaw rate
                  false, false, false]

