slam_toolbox:
  ros__parameters:
    use_sim_time: false
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan
    use_imu: false

    # 권장 추가/수정
    min_laser_range: 0.1
    max_laser_range: 16.0
    transform_tolerance: 0.2      # TF 약간 여유
    resolution: 0.05
    map_update_interval: 2.0
